language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - .cache
  - node_modules
script:
- yarn build --public-url /yapp/
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GH_TOKEN # create a personal access token, save it in the setting on TravisCI (set to secure so it won't be logged)
  on:
    branch: master
notifications:
  email: false
